import type { IFormTheme } from "@/shared/types/common"

/**
 * A named, ready-to-apply form theme shown in the Design drawer's Themes tab.
 *
 * Every preset is a complete `IFormTheme`, so applying one replaces the whole
 * draft rather than merging: a partial preset would leave stale colours from
 * the previous theme and make the result unpredictable.
 */
export interface ThemePreset {
    id: string
    name: string
    /** Short grouping label shown beside the name on the card. */
    mood: "Light" | "Dark" | "Bold" | "Photo"
    theme: IFormTheme
}

/** Unsplash URLs are built at a fixed width so preview thumbnails stay light. */
const photo = (id: string) =>
    `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1600&q=70`

/**
 * Presets are spelled out in full rather than composed from a base, so each one
 * can be read and tweaked in isolation.
 *
 * `backgroundImage.brightness` is an offset applied as
 * `brightness((100 + value) / 100)`, so negative values darken the photo. Photo
 * presets darken enough for light text to stay readable.
 */
export const THEME_PRESETS: readonly ThemePreset[] = [
    // ---------------------------------------------------------------- Light
    {
        id: "classic-mono",
        name: "Classic Mono",
        mood: "Light",
        theme: {
            primaryColor: "#000000",
            backgroundColor: "#ffffff",
            textColor: "#111111",
            questionColor: "#111111",
            answerColor: "#111111",
            buttonColor: "#000000",
            buttonTextColor: "#ffffff",
            alignment: "left",
            fontSize: "medium",
            roundCorners: "medium",
            font: { family: "Inter", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "editorial-coral",
        name: "Editorial Coral",
        mood: "Light",
        theme: {
            primaryColor: "#ee7d69",
            backgroundColor: "#fffdfb",
            textColor: "#2e2825",
            questionColor: "#2e2825",
            answerColor: "#665f5b",
            buttonColor: "#ee7d69",
            buttonTextColor: "#ffffff",
            alignment: "left",
            fontSize: "medium",
            roundCorners: "large",
            font: { family: "Inter", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "warm-sand",
        name: "Warm Sand",
        mood: "Light",
        theme: {
            primaryColor: "#b4703f",
            backgroundColor: "#f8f3ec",
            textColor: "#3d332a",
            questionColor: "#3d332a",
            answerColor: "#6b5b4b",
            buttonColor: "#b4703f",
            buttonTextColor: "#fffaf4",
            alignment: "center",
            fontSize: "medium",
            roundCorners: "full",
            font: { family: "Lora", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "sage-calm",
        name: "Sage Calm",
        mood: "Light",
        theme: {
            primaryColor: "#4f7a63",
            backgroundColor: "#f2f6f2",
            textColor: "#25332c",
            questionColor: "#25332c",
            answerColor: "#4d5f55",
            buttonColor: "#4f7a63",
            buttonTextColor: "#ffffff",
            alignment: "left",
            fontSize: "medium",
            roundCorners: "large",
            font: { family: "Outfit", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "sky-clean",
        name: "Sky Clean",
        mood: "Light",
        theme: {
            primaryColor: "#2f6fdb",
            backgroundColor: "#f5f9ff",
            textColor: "#12233d",
            questionColor: "#12233d",
            answerColor: "#40546f",
            buttonColor: "#2f6fdb",
            buttonTextColor: "#ffffff",
            alignment: "left",
            fontSize: "medium",
            roundCorners: "medium",
            font: { family: "Plus Jakarta Sans", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "blush-serif",
        name: "Blush Serif",
        mood: "Light",
        theme: {
            primaryColor: "#b5476a",
            backgroundColor: "#fdf4f6",
            textColor: "#3b1f29",
            questionColor: "#3b1f29",
            answerColor: "#6d4b57",
            buttonColor: "#b5476a",
            buttonTextColor: "#ffffff",
            alignment: "center",
            fontSize: "large",
            roundCorners: "full",
            font: { family: "Playfair Display", source: "google" },
            backgroundImage: null,
        },
    },
    // ----------------------------------------------------------------- Dark
    {
        id: "midnight-ink",
        name: "Midnight Ink",
        mood: "Dark",
        theme: {
            primaryColor: "#7aa2f7",
            backgroundColor: "#12141c",
            textColor: "#e6e8f0",
            questionColor: "#f2f4fa",
            answerColor: "#b6bccd",
            buttonColor: "#7aa2f7",
            buttonTextColor: "#101320",
            alignment: "left",
            fontSize: "medium",
            roundCorners: "medium",
            font: { family: "Inter", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "charcoal-lime",
        name: "Charcoal Lime",
        mood: "Dark",
        theme: {
            primaryColor: "#c2f04b",
            backgroundColor: "#1b1d1a",
            textColor: "#eef2e6",
            questionColor: "#f4f8ec",
            answerColor: "#b7bfae",
            buttonColor: "#c2f04b",
            buttonTextColor: "#1b1d1a",
            alignment: "left",
            fontSize: "large",
            roundCorners: "full",
            font: { family: "Space Grotesk", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "deep-forest",
        name: "Deep Forest",
        mood: "Dark",
        theme: {
            primaryColor: "#7fd1a4",
            backgroundColor: "#0f1c17",
            textColor: "#e3f0e9",
            questionColor: "#eaf6ef",
            answerColor: "#a9c2b6",
            buttonColor: "#7fd1a4",
            buttonTextColor: "#0f1c17",
            alignment: "center",
            fontSize: "medium",
            roundCorners: "large",
            font: { family: "Outfit", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "plum-noir",
        name: "Plum Noir",
        mood: "Dark",
        theme: {
            primaryColor: "#d8a3ff",
            backgroundColor: "#1a1220",
            textColor: "#ece3f4",
            questionColor: "#f4ecf9",
            answerColor: "#b8a8c6",
            buttonColor: "#d8a3ff",
            buttonTextColor: "#1a1220",
            alignment: "left",
            fontSize: "medium",
            roundCorners: "large",
            font: { family: "Playfair Display", source: "google" },
            backgroundImage: null,
        },
    },
    // ----------------------------------------------------------------- Bold
    {
        id: "electric-violet",
        name: "Electric Violet",
        mood: "Bold",
        theme: {
            primaryColor: "#ffe14d",
            backgroundColor: "#4c1d95",
            textColor: "#f5f0ff",
            questionColor: "#ffffff",
            answerColor: "#d9cbf5",
            buttonColor: "#ffe14d",
            buttonTextColor: "#3b1178",
            alignment: "center",
            fontSize: "large",
            roundCorners: "full",
            font: { family: "Outfit", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "tangerine-pop",
        name: "Tangerine Pop",
        mood: "Bold",
        theme: {
            primaryColor: "#1b1b1b",
            backgroundColor: "#ff7a29",
            textColor: "#2a1200",
            questionColor: "#1b0d00",
            answerColor: "#5c2c07",
            buttonColor: "#1b1b1b",
            buttonTextColor: "#ffd9bd",
            alignment: "left",
            fontSize: "large",
            roundCorners: "none",
            font: { family: "Space Grotesk", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "ocean-teal",
        name: "Ocean Teal",
        mood: "Bold",
        theme: {
            primaryColor: "#ffffff",
            backgroundColor: "#0f7b8a",
            textColor: "#eafbfd",
            questionColor: "#ffffff",
            answerColor: "#c2e9ef",
            buttonColor: "#ffffff",
            buttonTextColor: "#0b5c68",
            alignment: "center",
            fontSize: "medium",
            roundCorners: "full",
            font: { family: "Plus Jakarta Sans", source: "google" },
            backgroundImage: null,
        },
    },
    {
        id: "crimson-serif",
        name: "Crimson Serif",
        mood: "Bold",
        theme: {
            primaryColor: "#ffd9d0",
            backgroundColor: "#8c1d2f",
            textColor: "#fdeef0",
            questionColor: "#ffffff",
            answerColor: "#eec4c9",
            buttonColor: "#ffd9d0",
            buttonTextColor: "#6c101f",
            alignment: "center",
            fontSize: "large",
            roundCorners: "medium",
            font: { family: "Playfair Display", source: "google" },
            backgroundImage: null,
        },
    },
    // ---------------------------------------------------------------- Photo
    {
        id: "mountain-haze",
        name: "Mountain Haze",
        mood: "Photo",
        theme: {
            primaryColor: "#ffffff",
            backgroundColor: "#1d2733",
            textColor: "#f4f7fb",
            questionColor: "#ffffff",
            answerColor: "#dbe4ee",
            buttonColor: "#ffffff",
            buttonTextColor: "#1d2733",
            alignment: "center",
            fontSize: "large",
            roundCorners: "full",
            font: { family: "Inter", source: "google" },
            backgroundImage: {
                url: photo("1506905925346-21bda4d32df4"),
                alt: "Misty mountain range at dawn",
                brightness: -35,
                tile: false,
            },
        },
    },
    {
        id: "forest-canopy",
        name: "Forest Canopy",
        mood: "Photo",
        theme: {
            primaryColor: "#d8f5c8",
            backgroundColor: "#16241a",
            textColor: "#eef7ea",
            questionColor: "#ffffff",
            answerColor: "#d3e4cd",
            buttonColor: "#d8f5c8",
            buttonTextColor: "#1c2f1f",
            alignment: "left",
            fontSize: "large",
            roundCorners: "large",
            font: { family: "Outfit", source: "google" },
            backgroundImage: {
                url: photo("1441974231531-c6227db76b6e"),
                alt: "Sunlight through a green forest canopy",
                brightness: -40,
                tile: false,
            },
        },
    },
    {
        id: "desert-dune",
        name: "Desert Dune",
        mood: "Photo",
        theme: {
            primaryColor: "#ffe9c9",
            backgroundColor: "#3d2a1c",
            textColor: "#fdf3e8",
            questionColor: "#ffffff",
            answerColor: "#ecd9c4",
            buttonColor: "#ffe9c9",
            buttonTextColor: "#4a3220",
            alignment: "center",
            fontSize: "large",
            roundCorners: "full",
            font: { family: "Lora", source: "google" },
            backgroundImage: {
                url: photo("1509316785289-025f5b846b35"),
                alt: "Rippled sand dunes",
                brightness: -30,
                tile: false,
            },
        },
    },
    {
        id: "night-city",
        name: "Night City",
        mood: "Photo",
        theme: {
            primaryColor: "#8ab4ff",
            backgroundColor: "#0c1220",
            textColor: "#e9eefb",
            questionColor: "#ffffff",
            answerColor: "#c3cee6",
            buttonColor: "#8ab4ff",
            buttonTextColor: "#0c1220",
            alignment: "left",
            fontSize: "medium",
            roundCorners: "medium",
            font: { family: "Space Grotesk", source: "google" },
            backgroundImage: {
                url: photo("1470071459604-3b5ec3a7fe05"),
                alt: "City skyline at night",
                brightness: -45,
                tile: false,
            },
        },
    },
    {
        id: "coastal-calm",
        name: "Coastal Calm",
        mood: "Photo",
        theme: {
            primaryColor: "#ffffff",
            backgroundColor: "#14343f",
            textColor: "#eef8fa",
            questionColor: "#ffffff",
            answerColor: "#cfe5eb",
            buttonColor: "#ffffff",
            buttonTextColor: "#14343f",
            alignment: "center",
            fontSize: "medium",
            roundCorners: "full",
            font: { family: "Plus Jakarta Sans", source: "google" },
            backgroundImage: {
                url: photo("1507525428034-b723cf961d3e"),
                alt: "Calm turquoise shoreline",
                brightness: -30,
                tile: false,
            },
        },
    },
    {
        id: "studio-marble",
        name: "Studio Marble",
        mood: "Photo",
        theme: {
            primaryColor: "#1f1f1f",
            backgroundColor: "#f3f0ec",
            textColor: "#1f1c1a",
            questionColor: "#141210",
            answerColor: "#4a443f",
            buttonColor: "#1f1f1f",
            buttonTextColor: "#ffffff",
            alignment: "left",
            fontSize: "medium",
            roundCorners: "medium",
            font: { family: "Inter", source: "google" },
            backgroundImage: {
                url: photo("1618221195710-dd6b41faaea6"),
                alt: "Soft white marble texture",
                brightness: 10,
                tile: false,
            },
        },
    },
]

/** Lookup used to mark the active card when a draft matches a preset. */
export const THEME_PRESETS_BY_ID: ReadonlyMap<string, ThemePreset> = new Map(
    THEME_PRESETS.map((preset) => [preset.id, preset])
)
