export const ROUTES = {
    HOME: "/",
    LOGIN: "/login",
    SIGNUP: "/signup",
    FORGOT_PASSWORD: "/forgot-password",
    DASHBOARD: "/dashboard",
    FORMS: "/forms",
    TEMPLATES: "/templates",
    SETTINGS: "/settings",
    PRICING: "/pricing",
    FORM_BUILDER: "/form-builder/:formId",
    FORM_SETTINGS: "/form-settings/:formId",
    FORM_INTEGRATIONS: "/form-integrate/:formId",
    FORM_SHARE: "/form-share/:formId",
    FORM_RESPONSE_SUBMISSIONS: "/form-response/:formId/submissions",
    FORM_RESPONSE_SUMMARY: "/form-response/:formId/summary",
    FORM_RESPONSE_ANALYTICS: "/form-response/:formId/analytics",
    FORM_PREVIEW: "/form-preview/:formId",
    FORM_FILL: "/form/:slug",
} as const