import type { Form, FormField, FormResponse, User } from "../types/common"

export const mockUser: User = {
    _id: "user_1",
    name: "Alex Morgan",
    email: "alex@example.com",
    avatarUrl: "",
    role: "admin",
    isActive: true,
    lastLoginAt: "2026-07-26T10:30:00Z",
}

export const mockFields: FormField[] = [
    {
        _id: "field_1",
        formId: "form_1",
        fieldKey: "full_name",
        label: "Full Name",
        helperText: "Enter your first and last name",
        placeholder: "John Doe",
        type: "shortText",
        required: true,
        order: 1,
        options: [],
        logic: [],
        appearance: { width: "full" },
        isActive: true,
    },
    {
        _id: "field_2",
        formId: "form_1",
        fieldKey: "email",
        label: "Email Address",
        helperText: "We'll never share your email",
        placeholder: "you@example.com",
        type: "email",
        required: true,
        order: 2,
        options: [],
        logic: [],
        appearance: { width: "full" },
        isActive: true,
    },
    {
        _id: "field_3",
        formId: "form_1",
        fieldKey: "age",
        label: "Age",
        helperText: "",
        placeholder: "25",
        type: "number",
        required: false,
        order: 3,
        options: [],
        validation: { min: 1, max: 120, message: "Enter a valid age" },
        logic: [],
        appearance: { width: "half" },
        isActive: true,
    },
    {
        _id: "field_4",
        formId: "form_1",
        fieldKey: "feedback_type",
        label: "Feedback Type",
        helperText: "What kind of feedback do you have?",
        placeholder: "",
        type: "select",
        required: true,
        order: 4,
        options: [
            { label: "Bug Report", value: "bug" },
            { label: "Feature Request", value: "feature" },
            { label: "General Feedback", value: "general" },
            { label: "Other", value: "other" },
        ],
        logic: [],
        appearance: { width: "full" },
        isActive: true,
    },
    {
        _id: "field_5",
        formId: "form_1",
        fieldKey: "rating",
        label: "How would you rate your experience?",
        helperText: "1 = Poor, 5 = Excellent",
        placeholder: "",
        type: "rating",
        required: true,
        order: 5,
        options: [],
        logic: [],
        appearance: { width: "full" },
        isActive: true,
    },
    {
        _id: "field_6",
        formId: "form_1",
        fieldKey: "comments",
        label: "Additional Comments",
        helperText: "Anything else you'd like to share?",
        placeholder: "Write your comments here...",
        type: "longText",
        required: false,
        order: 6,
        options: [],
        validation: { maxLength: 1000, message: "Max 1000 characters" },
        logic: [],
        appearance: { width: "full" },
        isActive: true,
    },
    {
        _id: "field_7",
        formId: "form_1",
        fieldKey: "subscribe",
        label: "Subscribe to newsletter",
        helperText: "",
        placeholder: "",
        type: "yesNo",
        required: true,
        order: 7,
        options: [],
        logic: [],
        appearance: { width: "full" },
        isActive: true,
    },
    {
        _id: "field_8",
        formId: "form_1",
        fieldKey: "preferred_contact",
        label: "Preferred Contact Method",
        helperText: "How should we reach you?",
        placeholder: "",
        type: "checkbox",
        required: false,
        order: 8,
        options: [
            { label: "Email", value: "email" },
            { label: "Phone", value: "phone" },
            { label: "SMS", value: "sms" },
        ],
        logic: [],
        appearance: { width: "full" },
        isActive: true,
    },
]

export const mockForms: Form[] = [
    {
        _id: "form_1",
        title: "Customer Feedback Survey",
        description: "Help us improve our product by sharing your experience",
        slug: "customer-feedback-survey",
        status: "published",
        theme: {
            primaryColor: "#6366f1",
            backgroundColor: "#ffffff",
            textColor: "#111827",
        },
        settings: {
            oneQuestionAtATime: true,
            showProgressBar: true,
            allowMultipleSubmissions: false,
            requireLogin: false,
            collectIP: false,
        },
        createdBy: "user_1",
        fields: mockFields,
        createdAt: "2026-07-20T08:00:00Z",
        updatedAt: "2026-07-25T14:30:00Z",
    },
    {
        _id: "form_2",
        title: "Job Application Form",
        description: "Apply for open positions at our company",
        slug: "job-application",
        status: "published",
        theme: {
            primaryColor: "#0891b2",
            backgroundColor: "#f8fafc",
            textColor: "#0f172a",
        },
        settings: {
            oneQuestionAtATime: false,
            showProgressBar: true,
            allowMultipleSubmissions: false,
            requireLogin: true,
            collectIP: true,
        },
        createdBy: "user_1",
        fields: [
            {
                _id: "field_j1",
                formId: "form_2",
                fieldKey: "first_name",
                label: "First Name",
                helperText: "",
                placeholder: "John",
                type: "shortText",
                required: true,
                order: 1,
                options: [],
                logic: [],
                appearance: { width: "half" },
                isActive: true,
            },
            {
                _id: "field_j2",
                formId: "form_2",
                fieldKey: "last_name",
                label: "Last Name",
                helperText: "",
                placeholder: "Doe",
                type: "shortText",
                required: true,
                order: 2,
                options: [],
                logic: [],
                appearance: { width: "half" },
                isActive: true,
            },
            {
                _id: "field_j3",
                formId: "form_2",
                fieldKey: "email_job",
                label: "Email",
                helperText: "",
                placeholder: "john@example.com",
                type: "email",
                required: true,
                order: 3,
                options: [],
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
            {
                _id: "field_j4",
                formId: "form_2",
                fieldKey: "phone_job",
                label: "Phone Number",
                helperText: "",
                placeholder: "+1 555-1234",
                type: "phone",
                required: true,
                order: 4,
                options: [],
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
            {
                _id: "field_j5",
                formId: "form_2",
                fieldKey: "position",
                label: "Position Applied For",
                helperText: "",
                placeholder: "Select a position",
                type: "select",
                required: true,
                order: 5,
                options: [
                    { label: "Frontend Developer", value: "frontend" },
                    { label: "Backend Developer", value: "backend" },
                    { label: "Full Stack Developer", value: "fullstack" },
                    { label: "Designer", value: "designer" },
                    { label: "Product Manager", value: "pm" },
                ],
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
            {
                _id: "field_j6",
                formId: "form_2",
                fieldKey: "start_date",
                label: "Earliest Start Date",
                helperText: "",
                placeholder: "",
                type: "date",
                required: true,
                order: 6,
                options: [],
                logic: [],
                appearance: { width: "half" },
                isActive: true,
            },
            {
                _id: "field_j7",
                formId: "form_2",
                fieldKey: "cover_letter",
                label: "Cover Letter",
                helperText: "Tell us why you're a good fit",
                placeholder: "Write your cover letter...",
                type: "longText",
                required: true,
                order: 7,
                options: [],
                validation: { maxLength: 5000, message: "Max 5000 characters" },
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
            {
                _id: "field_j8",
                formId: "form_2",
                fieldKey: "resume",
                label: "Upload Resume",
                helperText: "PDF or DOCX, max 5MB",
                placeholder: "",
                type: "file",
                required: true,
                order: 8,
                options: [],
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
        ],
        createdAt: "2026-07-18T10:00:00Z",
        updatedAt: "2026-07-22T09:15:00Z",
    },
    {
        _id: "form_3",
        title: "Event Registration",
        description: "Register for the Annual Tech Conference 2026",
        slug: "event-registration-2026",
        status: "draft",
        theme: {
            primaryColor: "#8b5cf6",
            backgroundColor: "#ffffff",
            textColor: "#1e1b4b",
        },
        settings: {
            oneQuestionAtATime: true,
            showProgressBar: true,
            allowMultipleSubmissions: false,
            requireLogin: false,
            collectIP: false,
        },
        createdBy: "user_1",
        fields: [
            {
                _id: "field_e1",
                formId: "form_3",
                fieldKey: "attendee_name",
                label: "Full Name",
                helperText: "",
                placeholder: "Jane Smith",
                type: "shortText",
                required: true,
                order: 1,
                options: [],
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
            {
                _id: "field_e2",
                formId: "form_3",
                fieldKey: "attendee_email",
                label: "Email",
                helperText: "We'll send your ticket via email",
                placeholder: "jane@example.com",
                type: "email",
                required: true,
                order: 2,
                options: [],
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
            {
                _id: "field_e3",
                formId: "form_3",
                fieldKey: "ticket_type",
                label: "Ticket Type",
                helperText: "",
                placeholder: "",
                type: "radio",
                required: true,
                order: 3,
                options: [
                    { label: "General Admission - $99", value: "general" },
                    { label: "VIP - $249", value: "vip" },
                    { label: "Student - $49", value: "student" },
                ],
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
            {
                _id: "field_e4",
                formId: "form_3",
                fieldKey: "dietary",
                label: "Dietary Requirements",
                helperText: "Select all that apply",
                placeholder: "",
                type: "multiSelect",
                required: false,
                order: 4,
                options: [
                    { label: "Vegetarian", value: "vegetarian" },
                    { label: "Vegan", value: "vegan" },
                    { label: "Gluten-Free", value: "gluten_free" },
                    { label: "Nut Allergy", value: "nut_allergy" },
                    { label: "None", value: "none" },
                ],
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
            {
                _id: "field_e5",
                formId: "form_3",
                fieldKey: "workshop",
                label: "Which workshop would you like to attend?",
                helperText: "",
                placeholder: "",
                type: "select",
                required: true,
                order: 5,
                options: [
                    { label: "AI & Machine Learning", value: "ai_ml" },
                    { label: "Cloud Architecture", value: "cloud" },
                    { label: "Web Development", value: "web_dev" },
                    { label: "Cybersecurity", value: "security" },
                ],
                logic: [],
                appearance: { width: "full" },
                isActive: true,
            },
        ],
        createdAt: "2026-07-26T12:00:00Z",
        updatedAt: "2026-07-26T12:00:00Z",
    },
]

export const mockResponses: FormResponse[] = [
    {
        _id: "resp_1",
        formId: "form_1",
        sessionId: "sess_abc123",
        answers: [
            { fieldKey: "full_name", label: "Full Name", type: "shortText", value: "Sarah Johnson" },
            { fieldKey: "email", label: "Email Address", type: "email", value: "sarah@example.com" },
            { fieldKey: "age", label: "Age", type: "number", value: 32 },
            { fieldKey: "feedback_type", label: "Feedback Type", type: "select", value: "feature" },
            { fieldKey: "rating", label: "How would you rate your experience?", type: "rating", value: 4 },
            { fieldKey: "comments", label: "Additional Comments", type: "longText", value: "Great product! Would love to see dark mode support." },
            { fieldKey: "subscribe", label: "Subscribe to newsletter", type: "yesNo", value: "Yes" },
            { fieldKey: "preferred_contact", label: "Preferred Contact Method", type: "checkbox", value: ["email", "sms"] },
        ],
        metadata: { ipAddress: "192.168.1.1", userAgent: "Mozilla/5.0", referrer: "", country: "US", city: "New York" },
        submittedAt: "2026-07-25T16:45:00Z",
    },
    {
        _id: "resp_2",
        formId: "form_1",
        sessionId: "sess_def456",
        answers: [
            { fieldKey: "full_name", label: "Full Name", type: "shortText", value: "Mike Chen" },
            { fieldKey: "email", label: "Email Address", type: "email", value: "mike@example.com" },
            { fieldKey: "age", label: "Age", type: "number", value: 28 },
            { fieldKey: "feedback_type", label: "Feedback Type", type: "select", value: "bug" },
            { fieldKey: "rating", label: "How would you rate your experience?", type: "rating", value: 3 },
            { fieldKey: "comments", label: "Additional Comments", type: "longText", value: "The login page crashes on Safari." },
            { fieldKey: "subscribe", label: "Subscribe to newsletter", type: "yesNo", value: "No" },
            { fieldKey: "preferred_contact", label: "Preferred Contact Method", type: "checkbox", value: ["email"] },
        ],
        metadata: { ipAddress: "192.168.1.2", userAgent: "Mozilla/5.0", referrer: "", country: "CA", city: "Toronto" },
        submittedAt: "2026-07-26T09:20:00Z",
    },
    {
        _id: "resp_3",
        formId: "form_1",
        sessionId: "sess_ghi789",
        answers: [
            { fieldKey: "full_name", label: "Full Name", type: "shortText", value: "Emily Davis" },
            { fieldKey: "email", label: "Email Address", type: "email", value: "emily@example.com" },
            { fieldKey: "age", label: "Age", type: "number", value: 45 },
            { fieldKey: "feedback_type", label: "Feedback Type", type: "select", value: "general" },
            { fieldKey: "rating", label: "How would you rate your experience?", type: "rating", value: 5 },
            { fieldKey: "comments", label: "Additional Comments", type: "longText", value: "Excellent service! Very satisfied." },
            { fieldKey: "subscribe", label: "Subscribe to newsletter", type: "yesNo", value: "Yes" },
            { fieldKey: "preferred_contact", label: "Preferred Contact Method", type: "checkbox", value: ["email", "phone"] },
        ],
        metadata: { ipAddress: "192.168.1.3", userAgent: "Mozilla/5.0", referrer: "", country: "UK", city: "London" },
        submittedAt: "2026-07-26T14:10:00Z",
    },
]